name: Build Native Libs

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version number (package)

permissions:
  packages: write
  contents: read

jobs:
  build-platforms:
      name: Build ${{ matrix.targetname }}-${{ matrix.arch }}
      runs-on: ${{ matrix.buildos }}

      env:
        CMAKE_BUILD_TYPE: Release

        TRIPLETS_DIR: ${{ github.workspace }}/native/build/triplets
        ARCHIVE_DIR: ${{ github.workspace }}/archive-${{ matrix.targetname }}
        BUILD_DIR: ${{ github.workspace }}/build-${{ matrix.arch }}

      strategy:
        fail-fast: false
        matrix:
          include:
            - { targetname: android, buildos: ubuntu-20.04, arch: x86_64, triplet: x64-android }
            #- { targetname: osx, buildos: macos-latest, arch: x64, triplet: release-osx-x64 }
            #- { targetname: osx, buildos: macos-latest, arch: arm64, triplet: release-osx-arm64 }
            #- { targetname: linux, buildos: ubuntu-20.04, arch: x64, triplet: release-linux-x64 }
            #- { targetname: linux, buildos: ubuntu-20.04, arch: arm64, triplet: release-linux-arm64 }
            #- { targetname: windows, buildos: windows-latest, arch: x64, triplet: x64-windows-release }
            #- { targetname: windows, buildos: windows-latest,  arch: arm64, triplet: release-windows-arm64 }

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
            fetch-depth: 0

        - name: Install Additional Packages (Ubuntu)
          if: matrix.buildos == 'ubuntu-20.04' && matrix.arch == 'arm64'
          run: |
            sudo apt-get update
            sudo apt-get install -y binutils-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-aarch64-linux-gnu

        - name: Install Additional Packages (Android)
          if: matrix.targetname == 'android'
          run: |
            wget -nv -O android-ndk.zip https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
            unzip -qq android-ndk.zip
            mv android-ndk-r25c android-ndk
            export TOOLCHAIN="${{ github.workspace }}/android-ndk/toolchains/llvm/prebuilt/linux-x86_64"
            export ANDROID_NDK_HOME="${{ github.workspace }}/android-ndk"

        - name: Setup VCPKG
          uses: lukka/run-vcpkg@v11

        - name: Setup CMake (Linux)
          if: matrix.targetname == 'linux'
          run: cmake -B ${{ env.BUILD_DIR }} -S . -DVCPKG_OVERLAY_TRIPLETS=${{ env.TRIPLETS_DIR }} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          env:
            CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/native/build/linux-${{ matrix.arch }}.cmake

        - name: Setup CMake (Android)
          if: matrix.targetname == 'android'
          run: |
            cmake -B ${{ env.BUILD_DIR }} -S . -DVCPKG_OVERLAY_TRIPLETS=${{ env.TRIPLETS_DIR }} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} -DANDROID_ABI=${{ matrix.arch }} -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${{ github.workspace }}/android-ndk/build/cmake/android.toolchain.cmake -DVCPKG_BUILD_TYPE=release -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LIBRARY_LINKAGE=dynamic
          env:
            CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/native/build/android-${{ matrix.arch }}.cmake            
            ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk

        - name: Setup CMake (Windows)
          if: matrix.targetname == 'windows'
          run: cmake -B ${{ env.BUILD_DIR }} -G "Visual Studio 17 2022" -A ${{ matrix.arch == 'arm64' && 'ARM64' || 'x64' }} -S . -DVCPKG_OVERLAY_TRIPLETS=${{ env.TRIPLETS_DIR }} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          env:
            CMAKE_TOOLCHAIN_FILE: ${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
              
        - name: Setup CMake (macOS)
          if: matrix.targetname == 'osx'
          run: cmake -B ${{ env.BUILD_DIR }} -G "Xcode" -S . -DVCPKG_OVERLAY_TRIPLETS=${{ env.TRIPLETS_DIR }} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          env:
            CMAKE_TOOLCHAIN_FILE: ${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
            CMAKE_OSX_ARCHITECTURES: ${{ matrix.arch == 'arm64' && 'arm64' || 'x86_64' }}

        - name: Build
          run: cmake --build ${{ env.BUILD_DIR }} --config Release

        - name: Prepare Directory
          run: mkdir ${{ env.ARCHIVE_DIR }}

        - name: Prepare Files (Linux)
          if: matrix.targetname == 'linux'
          run: |
            cp ${{ env.BUILD_DIR }}/libcsdl.so ${{ env.ARCHIVE_DIR }}
            cp ${{ env.BUILD_DIR }}/vcpkg_installed/${{ matrix.triplet }}/lib/libtorrent-rasterbar.so ${{ env.ARCHIVE_DIR }}/libtorrent-rasterbar.so.2.0

        - name: Prepare Files (Android)
          if: matrix.targetname == 'android'
          run: |
            cp ${{ env.BUILD_DIR }}/libcsdl.so ${{ env.ARCHIVE_DIR }}
            cp ${{ env.BUILD_DIR }}/vcpkg_installed/${{ matrix.triplet }}/lib/libtorrent-rasterbar.so ${{ env.ARCHIVE_DIR }}/libtorrent-rasterbar.so.2.0
        
        - name: Prepare Files (macOS)
          if: matrix.targetname == 'osx'
          run: |
            cp ${{ env.BUILD_DIR }}/Release/libcsdl.dylib ${{ env.ARCHIVE_DIR }}
            cp ${{ env.BUILD_DIR }}/vcpkg_installed/${{ matrix.triplet }}/lib/libtorrent-rasterbar.dylib ${{ env.ARCHIVE_DIR }}/libtorrent-rasterbar.2.0.dylib

        - name: Prepare Files (Windows)
          if: matrix.targetname == 'windows'
          run: cp ${{ env.BUILD_DIR }}/Release/*.dll ${{ env.ARCHIVE_DIR }}

        - name: Upload
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.targetname }}-${{ matrix.arch }}
            path: ${{ env.ARCHIVE_DIR }}/*

  package:
    name: Build Package
    runs-on: ubuntu-latest

    needs: [build-platforms]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: osx-x64
          path: native/nuget/runtimes/osx-x64/native

      - uses: actions/download-artifact@v4
        with:
          name: osx-arm64
          path: native/nuget/runtimes/osx-arm64/native

      - uses: actions/download-artifact@v4
        with:
          name: windows-x64
          path: native/nuget/runtimes/win-x64/native

      - uses: actions/download-artifact@v4
        with:
          name: windows-arm64
          path: native/nuget/runtimes/win-arm64/native

      - uses: actions/download-artifact@v4
        with:
          name: linux-x64
          path: native/nuget/runtimes/linux-x64/native

      - uses: actions/download-artifact@v4
        with:
          name: linux-arm64
          path: native/nuget/runtimes/linux-arm64/native

      - uses: actions/download-artifact@v4
        with:
          name: android-x64
          path: native/nuget/runtimes/android-x64/native
